#!/usr/bin/env bash

# Enable simple aliases to be sudo'ed. ("sudone"?)
# http://www.gnu.org/software/bash/manual/bashref.html#Aliases says: "If the
# last character of the alias value is a space or tab character, then the next
# command word following the alias is also checked for alias expansion."
alias sudo='sudo ';

# Be nice!
alias please='sudo'
alias plz='please'

# Auto-correct last input.
alias fuck='$(thefuck $(fc -ln -1))'

# Easier folder navigation.
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# I <3 u cask.
alias cask='brew cask'

# Shortcut to edit hosts file.
alias hosts='sudo $EDITOR /etc/hosts'

# Confirm before overwriting
# I know it is bad practice to override the default commands, but this is for
# my own safety. If you really want the original "instakill" versions, you can
# use "command rm", "\rm", or "/bin/rm" inside your own commands, aliases, or
# shell functions. Note that separate scripts are not affected by the aliases
# defined here.
#alias cp='cp -i';
#alias mv='mv -i';
#alias rm='rm -i';

# Detect which `ls` flavor is in use and use colored output.
if ls --color > /dev/null 2>&1; then # GNU `ls`
  colorflag="--color"
else # OS X `ls`
  colorflag="-G"
fi

alias ls='CLICOLOR_FORCE=1 ls -Fh ${colorflag}'

# List ALL files (colorized() in long format, show permissions in octal
alias la="ls -la | awk '
{
k=0;
for (i=0;i<=8;i++)
k+=((substr(\$1,i+2,1)~/[rwx]/)*2^(8-i));
if (k)
  printf(\"%0o \",k);
  print
}'"

# List only directories.
alias lsd='ls -l | grep "^d"'

# Git.
alias g="git"
alias h="history"

# Stopwatch
alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date'

# Get OS X Software Updates, update installed Ruby gems, Homebrew, npm, and their
# installed packages.
alias update='sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup; npm update -g; pipudate; gem update --system; gem update;'

# What's my IP address.
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"

# Enhanced WHOIS lookups.
alias whois="whois -h whois.internic.net"

# OS X checksum fallbacks.
command -v md5sum > /dev/null || alias md5sum="md5"
command -v sha1sum > /dev/null || alias sha1sum="shasum"

# Empty the Trash on all mounted volumes and the main HDD. Also, clear Apple’s
# System Logs to improve shell startup speed
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

# Show/hide hidden files in Finder.
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons.
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# Kill all the tabs in Chrome to free up memory.
# [C] explained: http://www.commandlinefu.com/commands/view/402/exclude-grep-from-your-grepped-output-of-ps-alias-included-in-description
alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"

# Lock the screen (when going AFK).
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# Currency conversions.
alias usd="cconv 1 usd uah"
alias uah="cconv 1 uah usd"

# Update all Python packages installed via Pip.
alias pipupdate="pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip3 install -U"

# Chaturbate records
function chatrec(){
  livestreamer -p 'mpv --stream-capture=$1_$RANDOM.mp4 --title=$1 --cache 8192' chaturbate.com/$1 best
}
