#!/usr/bin/env bash

# Enable simple aliases to be sudo'ed. ("sudone"?)
# http://www.gnu.org/software/bash/manual/bashref.html#Aliases says: "If the
# last character of the alias value is a space or tab character, then the next
# command word following the alias is also checked for alias expansion."
alias sudo='sudo ';

# Be nice!
alias please='sudo'
alias plz='please'

# Auto-correct last input.
alias fuck='$(thefuck $(fc -ln -1))'

# Easier folder navigation.
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# Shortcut to edit hosts file.
alias hosts='sudo $EDITOR /etc/hosts'

# Confirm before overwriting
# I know it is bad practice to override the default commands, but this is for
# my own safety. If you really want the original "instakill" versions, you can
# use "command rm", "\rm", or "/bin/rm" inside your own commands, aliases, or
# shell functions. Note that separate scripts are not affected by the aliases
# defined here.
#alias cp='cp -i';
#alias mv='mv -i';
#alias rm='rm -i';

# Detect which `ls` flavor is in use and use colored output.
if ls --color > /dev/null 2>&1; then # GNU `ls`
  colorflag="--color"
else # OS X `ls`
  colorflag="-G"
fi

alias ls='CLICOLOR_FORCE=1 ls -Fh ${colorflag}'

# List ALL files (colorized() in long format, show permissions in octal
alias la="ls -la | awk '
{
k=0;
for (i=0;i<=8;i++)
k+=((substr(\$1,i+2,1)~/[rwx]/)*2^(8-i));
if (k)
  printf(\"%0o \",k);
  print
}'"

# List only directories.
alias lsd='ls -l | grep "^d"'

# Git.
alias g="git"
alias h="history"

# Stopwatch
alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date'

# Get OS X Software Updates, update installed Ruby gems, Homebrew, npm, and their
# installed packages.
alias update='sudo apt-get update; sudo apt-get upgrade; sudo apt-get autoclean; npm update -g; pipudate;'

# What's my IP address.
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"

# Enhanced WHOIS lookups.
alias whois="whois -h whois.internic.net"

# OS X checksum fallbacks.
command -v md5sum > /dev/null || alias md5sum="md5"
command -v sha1sum > /dev/null || alias sha1sum="shasum"

# Currency conversions.
alias usd="cconv 1 usd uah"
alias eur="cconv 1 uah usd"

# Update all Python packages installed via Pip.
alias pipudate="pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip3 install -U"
